docker-compose-yaml: docker-compose.yml

environments:
  main:
    network-policies:
    - service: nginx
      projects: 
      # this allows only the production environment from frontend-test to access nginx
      - name: frontend-test
        environment-type: production
